src/Opit/OpitHrm/UserBundle/Entity/User.php
<?php

/*
 *  This file is part of the OPIT-HRM project.
 *
 *  (c) Opit Consulting Kft. <info@opit.hu>
 *
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */

namespace Opit\OpitHrm\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Opit\OpitHrm\TravelBundle\Model\TravelRequestUserInterface;
use Opit\OpitHrm\NotificationBundle\Model\NotificationUserInterface;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Description of User
 * Custom user entity to validata against a database
 *
 * @author OPIT Consulting Kft. - PHP Team - {@link http://www.opit.hu}
 * @version 1.0
 * @package OPIT-HRM
 * @subpackage UserBundle
 *
 * @internal Must be implemented the: User, General Manager and Travel manager requests.
 *
 * @ORM\Table(name="opithrm_users")
 * @ORM\Entity(repositoryClass="Opit\OpitHrm\UserBundle\Entity\UserRepository")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @UniqueEntity(fields={"username"}, message="The username is already used.", groups={"user"})
 * @UniqueEntity(fields={"email"}, message="The email is already used.", groups={"user"})
 */
class User implements AdvancedUserInterface, \Serializable, TravelRequestUserInterface, NotificationUserInterface
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\NotBlank(message="The username can not be blank.", groups={"user"})
     */
    protected $username;

    /**
     * @ORM\OneToOne(targetEntity="Employee", inversedBy="user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="employee_id", referencedColumnName="id")
     * @Assert\Valid
     */
    protected $employee;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $salt;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank(message="The password can not be blank.", groups={"password"})
     * @Assert\Length(
     *      min = "6",
     *      max = "50",
     *      minMessage = "The password must be greater or equal to {{ limit }} characters",
     *      maxMessage = "The password must be less or equal to {{ limit }} characters",
     *      groups={"password"}
     * )
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=60)
     * @Assert\NotBlank(message="The email can not be blank.", groups={"user", "password"})
     * @Assert\Email(message = "The email '{{ value }}' is not a valid email address.", groups={"user"})
     */
    protected $email;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\ManyToMany(targetEntity="Groups", inversedBy="users")
     * @ORM\JoinTable(name="opithrm_users_groups")
     */
    protected $groups;

    /**
     * User travel requests
     * @ORM\OneToMany(targetEntity="\Opit\OpitHrm\TravelBundle\Entity\TravelRequest", mappedBy="user", cascade={"remove"})
     */
    protected $userTravelRequests;

    /**
     * General manager travel requests
     * @ORM\OneToMany(targetEntity="\Opit\OpitHrm\TravelBundle\Entity\TravelRequest", mappedBy="generalManager", cascade={"remove"})
     */
    protected $gmTravelRequests;

    /**
     * Team manager travel requests
     * @ORM\OneToMany(targetEntity="\Opit\OpitHrm\TravelBundle\Entity\TravelRequest", mappedBy="teamManager", cascade={"remove"})
     */
    protected $tmTravelRequests;

    /**
     * General manager leave requests
     * @ORM\OneToMany(targetEntity="\Opit\OpitHrm\LeaveBundle\Entity\LeaveRequest", mappedBy="generalManager", cascade={"remove"})
     */
    protected $gmLeaveRequests;

    /**
     * Team manager leave requests
     * @ORM\OneToMany(targetEntity="\Opit\OpitHrm\LeaveBundle\Entity\LeaveRequest", mappedBy="teamManager", cascade={"remove"})
     */
    protected $tmLeaveRequests;

    /**
     * Hiring manager job positions
     * @ORM\OneToMany(targetEntity="\Opit\OpitHrm\HiringBundle\Entity\JobPosition", mappedBy="hiringManager", cascade={"remove"})
     */
    protected $hmJobPositions;

    /**
     * Notifications sent by user
     * @ORM\OneToMany(targetEntity="\Opit\OpitHrm\NotificationBundle\Entity\Notification", mappedBy="receiver", cascade={"remove"})
     */
    protected $notifications;

    /**
     * User travel expenses
     * @ORM\OneToMany(targetEntity="\Opit\OpitHrm\TravelBundle\Entity\TravelExpense", mappedBy="user", cascade={"remove"})
     */
    protected $userTravelExpenses;

    /**
     * @ORM\Column(name="is_first_login", type="boolean")
     */
    protected $isFirstLogin;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    protected $ldapEnabled;

    public function __construct()
    {
        //$this->salt = md5(uniqid(null, true));
        $this->isActive = true;
        $this->groups = new ArrayCollection();
        $this->userTravelRequests = new ArrayCollection();
        $this->gmTravelRequests = new ArrayCollection();
        $this->tmTravelRequests = new ArrayCollection();
        $this->gmLeaveRequests = new ArrayCollection();
        $this->hmJobPositions = new ArrayCollection();
        $this->userTravelExpenses = new ArrayCollection();
        $this->setSalt("");
        // Set ldap required to handle the default values mapped to not null properties.
        $this->setLdapEnabled(false);
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritDoc
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @inheritDoc
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @inheritDoc
     */
    public function getStatus()
    {
        return $this->isActive;
    }

    /**
     * @inheritDoc
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        return $this->groups->toArray();
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
    }

    /**
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            $this->isActive,
        ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            $this->isActive,
        ) = unserialize($serialized);
    }

    /**
     * Set username
     *
     * @param  string $username
     * @return User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Set salt
     *
     * @param  string $salt
     * @return User
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;

        return $this;
    }

    /**
     * Set password
     *
     * @param  string $password
     * @return User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Set isActive
     *
     * @param  boolean $isActive
     * @return User
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * Set email
     *
     * @param  string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Set role
     *
     * @param  string $role
     * @return User
     */
    public function setRoles($role)
    {
        $this->groups[] = $role;

        return $this;
    }

    /**
     * Add groups
     *
     * @param  \Opit\OpitHrm\UserBundle\Entity\Groups $groups
     * @return User
     */
    public function addGroup(\Opit\OpitHrm\UserBundle\Entity\Groups $groups)
    {
        $this->groups[] = $groups;

        return $this;
    }

    /**
     * Remove groups
     *
     * @param \Opit\OpitHrm\UserBundle\Entity\Groups $groups
     */
    public function removeGroup(\Opit\OpitHrm\UserBundle\Entity\Groups $groups)
    {
        $this->groups->removeElement($groups);
    }

    /**
     * Get groups
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGroups()
    {
        return $this->groups;
    }

    /**
     * Get deletedAt
     *
     * @return datetime
     */
    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    /**
     * Set deletedAt
     *
     * @param datetime $deletedAt
     */
    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * Set firstLogin
     *
     * @param  boolean $isFirstLogin
     * @return User
     */
    public function setIsFirstLogin($isFirstLogin)
    {
        $this->isFirstLogin = $isFirstLogin;

        return $this;
    }

    /**
     * Get firstLogin
     *
     * @return boolean
     */
    public function getIsFirstLogin()
    {
        return $this->isFirstLogin;
    }

    /**
     * Set ldapEnabled

src/Opit/OpitHrm/UserBundle/Form/UserType.php
<?php

/*
 *  This file is part of the OPIT-HRM project.
 * 
 *  (c) Opit Consulting Kft. <info@opit.hu>
 * 
 *  For the full copyright and license information, please view the LICENSE
 *  file that was distributed with this source code.
 */

namespace Opit\OpitHrm\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Description of UserType
 *
 * @author OPIT Consulting Kft. - PHP Team - {@link http://www.opit.hu}
 * @version 1.0
 * @package OPIT-HRM
 * @subpackage UserBundle
 */
class UserType extends AbstractType
{
    /**
     * Builds a form with given fields.
     *
     * @param object  $builder A Formbuilder interface object
     * @param array   $options An array of options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('_username', 'text', array('attr' => array(
            'placeholder' => 'Username'
        )));
        $builder->add('_password', 'password', array('attr' => array(
            'placeholder' => 'Password'
        )));
        $builder->add('login', 'submit');
    }
    
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => null,
        ));
    }

    public function getName()
    {
        return '';
    }
}

src/Opit/OpitHrm/UserBundle/Resources/views/User/_changePasswordForm.html.twig
{% form_theme form 'OpitOpitHrmUserBundle:Form:form_template.html.twig' %}

<h2 class="dialog-h2 hidden">Reset Password</h2>
<div class="dialog-description">Reset password of the user</div>
<div id="reply-message"></div>
<div class="error-message">
    {{ form_errors(form) }}
</div>
{{ form_start(form, {'attr': { 'id': 'changePassword_frm'}, 'method': 'POST'}) }}
    <div class="modalwindow default-border height-auto overflow-hidden">
        {{ form_widget(form) }}
    </div>
{{ form_end(form) }}

src/Opit/OpitHrm/UserBundle/Resources/views/User/_list.html.twig
<form class="delete-checkbox-form">
    <table id="list-table" class="width-100 list-table">
        <tr>
            <th class="width-24-fix"><i class="fa fa-trash-o fa-1x" title="Select/Deselect all"></i></th>
            <th>
                <i class="fa fa-sort default-right" data-field="u.username"></i>
                <span class="order-text cursor-pointer">Username</span>
            </th>
            <th>
                <i class="fa fa-sort default-right" data-field="u.email"></i>
                <span class="order-text cursor-pointer">Email</span>
            </th>
            <th>
                <i class="fa fa-sort default-right" data-field="e.employeeName"></i>
                <span class="order-text cursor-pointer">Employee Name</span>
            </th>
            <th>
                <i class="fa fa-sort default-right" data-field="u.isActive"></i>
                <span class="order-text cursor-pointer">Is Active</span>
            </th>
            <th>
                <i class="fa fa-sort default-right" data-field="u.ldapEnabled"></i>
                <span class="order-text cursor-pointer">Ldap Enabled</span>
            </th>
            <th>
                <span class="order-text cursor-pointer">Roles</span>
            </th>
            <th>Leave Entitlement</th>
            <th>Actions</th>
        </tr>
        {% for user in users %}
            {% set isDeleteable = is_granted('DELETE', user) %}
            {% set isEditable = is_granted('EDIT', user) %}
        <tr>
            <td class="width-24-fix">
                <input name="delete-user[]" type="checkbox" class="deleteMultiple" {% if not isDeleteable %}disabled="disabled"{% endif %} value="{{ user.id }}" {% if user.id == app.user.id %}disabled="disabled"{% endif %}>
            </td>
            <td>
                <span {% if isEditable %}class="list-username clickable text-decoration-underline cursor-pointer" data-user-id="{{ user.id }}"{% endif %}>
                    {{ user.username }}
                </span>
            </td>
            <td>{{ user.email }}</td>
            <td>{{ user.employee.employeeName }}</td>
            <td>
                {% if user.isActive %}<i class="fa fa-check font-size-d8-em"></i>{% endif %}
            </td>
            <td>
                {% if user.ldapEnabled %}<i class="fa fa-check font-size-d8-em"></i>{% endif %}
            </td>
            <td>
                {% for role in user.roles %}
                    {{ role.name }}{% if loop.index != user.roles|length %},{% endif %}
                {% endfor %}
            </td>
            <td>{{ leaveEntitlement[user.id] }}</td>
            <td>
                {% if isEditable %}
                <span class="reset-password clickable text-decoration-none cursor-pointer" data-user-id="{{ user.id }}" title="Reset password">
                    <i class="fa fa-undo"></i>
                </span>
                <span class="list-username clickable text-decoration-none cursor-pointer" data-user-id="{{ user.id }}" title="Edit user">
                    <i class="fa fa-pencil-square-o"></i>
                </span>
                {% endif %}
                {% if user.id != app.user.id %}
                    {% if isDeleteable %}
                    <span class="delete-single-user clickable text-decoration-none cursor-pointer" data-user-id="{{ user.id }}" title="Delete user">
                        <i class="fa fa-trash-o"></i>
                    </span>
                    {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
    {# Display a no results message #}
    {% if isSearch is defined %}
        {% include 'OpitOpitHrmCoreBundle:Shared:_emptyResult.html.twig' with { 'collection': users|length > 0 } %}
    {% endif %}

    {% if numberOfPages is defined and numberOfPages > 0 %}
        {% include 'OpitOpitHrmCoreBundle:Shared:_pager.html.twig' with
            {
                'numberOfPages': numberOfPages,
                'maxPages': maxPages,
                'offset': offset,
                'url': path('OpitOpitHrmUserBundle_user_list')
            }
        %}
    {% endif %}
</form>

src/Opit/OpitHrm/UserBundle/Resources/views/User/changePasswordForm.html.twig
{% extends '::base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
        '../app/Resources/public/css/updateStatus.scss'
    output='css/opithrmuser/status.css' filter='?yui_css,cssrewrite' %}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}
{% block body %}
<div class="align-center margin-bottom-10">
    <a href="{{ path('OpitOpitHrmUserBundle_user_show_infoboard') }}" id="siteLogo" class="text-decoration-none clearfix">
        <span class="display-block"><img src="{{ asset('images/logo.png') }}" width="105" alt="" /></span>
        <div class="clear"></div>
    </a>
</div>      
<div id="request-status">
<h2>Change password</h2>
<h4>
    You need to change your password before your first login into <a href="{{ path('OpitOpitHrmUserBundle_security_login') }}">OPIT-HRM</a>.
</h4>
    <div id="reply-message" class="alert-message error-message width-300 margin-center display-none">
        <i class="fa fa-exclamation-triangle"></i> <strong>Error messages:</strong>
    </div>
    {{ form(form, {
        'action': (path('OpitOpitHrmUserBundle_user_change_password', { 'id': app.request.get('id')})),
        'method': 'POST'
       })
    }}
</div>
{% endblock %}    
{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function(){
            $ul = $(document).find('ul');
            if ($ul.length > 0) {
                $('#reply-message').append($ul);
                $('#reply-message').toggleClass('display-none');
            }
        });
    </script>    
{% endblock %}

src/Opit/OpitHrm/UserBundle/Resources/views/User/list.html.twig
{% extends 'OpitOpitHrmCoreBundle::layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {% include '::_stylesheets.html.twig' %}
{% endblock %}

{% block title %}
    User list - {{ parent() }}
{% endblock %}
{% block body %}
<h1 class="margin-bottom-01em-important">User list</h1>
<div class="listing-description">Users for the portal can be managed from here.</div>
    {% include 'OpitOpitHrmUserBundle:Shared:_searchForm.html.twig' with { 'order_field': 'u.id' } %}
    <div id="userlistWrapper">
        <table>
            <tr>
                <td class="padding-left-0">
                    <button id="add" class="button"><i class="fa fa-plus-square fa-1x"></i>Add</button>
                    <button id="delete" class="button delete"><i class="fa fa-trash-o fa-1x"></i>Delete</button>
                </td>
            </tr>
        </table>
        <div id="list-reply-message"></div>
        <div id="user-list">
            {% include 'OpitOpitHrmUserBundle:User:_list.html.twig' %}
        </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts
        '@OpitOpitHrmCoreBundle/Resources/public/js/SearchForm.coffee'
        '@OpitOpitHrmUserBundle/Resources/public/js/list.coffee'
    output='js/opithrmuser/list.js' filter='?yui_js' %}
        <script type="text/javascript" src="{{ asset_url }}" ></script>
    {% endjavascripts %}
{% endblock %}

src/Opit/OpitHrm/UserBundle/Resources/views/User/showUserForm.html.twig
{% form_theme form 'OpitOpitHrmUserBundle:Form:form_template.html.twig' %}

{% if form.vars.value.getId() is not null %}
    {% set title = "Edit User"  %}
    {% set desc = "Edit an existing user." %}
{% else %}
    {% set title = "Create User"  %}
    {% set desc = "Create a new user." %}
{% endif %}
<h2 class="dialog-h2 hidden">{{ title|trans }}</h2>
<div class="dialog-description">{{desc|trans}}</div>
<div id="reply-message"></div>
<div class="error-message">
    {{ form_errors(form) }}
</div>
{{ form_start(form, {'attr': { 'id': 'adduser_frm'}, 'method': 'POST'}) }}
    <div class="modalwindow default-border height-auto overflow-hidden">
        {# form rendering is split because of subform layout nesting #}
        {% for key, value in form if key != 'employee' %}
            {{ form_row(value) }}
        {% endfor %}
        {# Employee related forms #}
        {% for key, value in form.employee %}
            {{ form_row(value) }}
        {% endfor %}
    </div>
{{ form_end(form) }}
{% block javascripts %}
    {% javascripts
        '@OpitOpitHrmCoreBundle/Resources/public/js/ToolTipHelp.coffee'
    output='js/opithrmcore/tooltiphelp.js' filter='?yui_js' %}
        <script type="text/javascript" src="{{ asset_url }}" ></script>
        {% endjavascripts %}
{% endblock %}
{# Date of birth requires individual options #}
<script type="text/javascript">
    var toolTipDescobj = {
            "idGroups" : "<table>This list can be modified from Administration->Roles</table>",
            "idJobTitle" : "This list can be modified from Administration->Job Titles",
            "idTeam": "This list can be modified from Administration->Team",
            "idJoiningDate" : "This value is considered while calculating employees annual leave entitlement",
            "idLeavingDate" : "This value is considered while generating time sheet",
            "idDob" : "This value is considered while calculating employees annual leave entitlement",
            "idNoc" : "This value is considered while calculating employees annual leave entitlement",
            "idReceiveNotifications" : "If set, this user will receive notifications for approved team member leave requests"
        };
        $(document).data('opithrm').funcs.helpToolTipDesc(toolTipDescobj);
        $(document).data('opithrm').funcs.showHideToolTip();
</script>

src/Opit/OpitHrm/UserBundle/Resources/views/User/showUserSummary.html.twig
{% extends 'OpitOpitHrmCoreBundle::layout.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
        'libs/fullcalendar/css/fullcalendar.css'
        '@OpitOpitHrmLeaveBundle/Resources/public/css/leaveCalendar.scss'
    output='css/opithrmuser/show_user_summary.css' filter='?yui_css,cssrewrite' %}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}
{% block title %}
    Employee Summary - {{ parent() }}
{% endblock %}
{% block body %}
<h1>Information Board</h1>
    <div id="employeeInfoWrapper" class="clearfix">
        <div class="float-left width-290 summary-box margin-right-5">
            <h3><i class="fa fa-user"></i>  Employee Info </h3>
            <table class="width-100">
                <tr>
                    <td class="width-32">Name:</td>
                    <td>{{ employee.employeeName|e }}</td>
                </tr>
                <tr>
                    <td>Joining:</td>
                    <td>{{ employee.joiningDate|date('d  F  Y') }}</td>
                </tr>
                <tr>
                    <td>Birth Date:</td>
                    <td>{{ employee.dateOfBirth|date('d  F  Y') }}</td>
                </tr>
                <tr>
                    <td>Children:</td>
                    <td>{{ employee.numberOfChildren|e }}</td>
                </tr>
                <tr>
                    <td>Tax-ID:</td>
                    <td>{{ employee.taxIdentification }}</td>
                </tr>
                <tr>
                    <td>Bank Name:</td>
                    <td>{{ employee.bankName|e }}</td>
                </tr>
                <tr>
                    <td>BAN:</td>
                    <td>{{ employee.bankAccountNumber|e }}</td>
                </tr>
                <tr>
                    <td>Job Title:</td>
                    <td>{%if employee.jobTitle.title is defined %}{{ employee.jobTitle.title|e }}{% endif %}</td>
                </tr>
                <tr>
                    <td>Work Hours:</td>
                    <td>{{ employee.workingHours|e }}</td>
                </tr>
            </table>
        </div>
        {% if bundleExist('OpitOpitHrmTravelBundle') %}
            {{ render(controller('OpitOpitHrmTravelBundle:Travel:employeeTravelInfoBoard')) }}
        {% endif %}
        {% if bundleExist('OpitOpitHrmLeaveBundle') %}
            {{ render(controller('OpitOpitHrmLeaveBundle:Leave:employeeLeavesinfoBoard')) }}
            <div class="clearfix"></div>
            {{ render(controller('OpitOpitHrmLeaveBundle:Calendar:showTeamLeavesCalendar', {
                'partial': true
            })) }}
        {% endif %}
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {% javascripts
        '@OpitOpitHrmUserBundle/Resources/public/js/list.coffee'
    output='js/opithrmuser/list.js' filter='?yui_js' %}
        <script type="text/javascript" src="{{ asset(asset_url) }}" ></script>
    {% endjavascripts %}
    {% if bundleExist('OpitOpitHrmLeaveBundle') %}
        {% javascripts
            'libs/fullcalendar/js/fullcalendar.min.js'
            '@OpitOpitHrmLeaveBundle/Resources/public/js/Calendar/teamLeavesCalendar.coffee'
            output='js/team_leaves_calendar.js' filter='?yui_js' %}
            <script type="text/javascript" src="{{ asset(asset_url) }}" ></script>
        {% endjavascripts %}
    {% endif %}
{% endblock %}